stages: [build, test, deploy, production]

build:
  image: docker:dind
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

test:
  image:
    name: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    entrypoint: ["/bin/sh", "-c"]
  stage: test
  variables:
    POSTGRES_DB: electeez
    POSTGRES_USER: electeez
    POSTGRES_PASSWORD: test
    DB_HOST: postgres
    DB_USER: electeez
    DB_PASS: test
    DB_NAME: electeez
    MEMCACHED_HOST: memcached
  services:
    - name: yourlabs/tezos
      alias: tz
    - name: memcached:1.6-alpine
    - name: postgres:latest
      command:
        - "postgres"
        - "-c"
        - "log_min_duration_statement=300"
  script:
    - pytest -sv

.deploy: &deploy
  image: yourlabs/ansible
  before_script:
    - mkdir -p ~/.ssh; echo "$MASTER_SSH_KEY" > ~/.ssh/id_ed25519; echo "$SSH_FINGERPRINTS" > ~/.ssh/known_hosts; chmod 700 ~/.ssh; chmod 600 ~/.ssh/*
  script:
    - export $(echo $MASTER_ENV | xargs)
    - export $(echo $SMTP | xargs)
    - export HOST=$(echo $CI_ENVIRONMENT_URL | sed s@^.*://@@)
    - export PROTO=$(echo $CI_ENVIRONMENT_URL | sed s@:.*@@)
    - DEFAULT_FROM_EMAIL=noreply@electeez.com
      ANSIBLE_FORCE_COLOR=1
      ANSIBLE_HOST_KEY_CHECKING=False
      bigsudo
        yourlabs.compose
        compose_django_image=$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
        compose_django_build=
        wait_grep=spawned.uWSGI.worker.1
        services=django
        $DEPLOY
        master@$HOST
        | tee deploy.log
    - grep unreachable=0 deploy.log &> /dev/null
    - grep failed=0 deploy.log &> /dev/null

# ephemeral branch deployment
review-deploy:
  <<: *deploy
  stage: test
  environment:
    name: test/$CI_COMMIT_REF_NAME
    url: http://${CI_ENVIRONMENT_SLUG}.$CI_PROJECT_NAME.ci.yourlabs.io
  variables:
    DEPLOY: >
      compose=docker-compose.yml
      lifetime=86400
      project=$CI_ENVIRONMENT_SLUG
  except:
  - tags
  - master

master:
  <<: *deploy
  stage: deploy
  environment:
    name: master
    url: https://master.electeez.com
  only:
    refs:
      - master
  variables:
    DEPLOY: >
      home=/home/master
      compose=docker-compose.yml,docker-compose.persist.yml

production:
  <<: *deploy
  stage: production
  environment:
    name: production
    url: https://electeez.com
  when: manual
  only:
    refs:
      - master
      - production
  variables:
    DEPLOY: >
      home=/home/production
      compose=docker-compose.yml,docker-compose.persist.yml
