version: "3.5"
services:
  django:
    restart: always
    volumes:
      - ./data/media:/app/media
      - ./spooler:/spooler
      - ./log:/app/log
      - ./data/ipfs:/app/.ipfs
    labels:
      - "io.yourlabs.compose.mkdir=/spooler,./data/media,./log,./data/ipfs:1000:1000:0750"
      - "traefik.http.middlewares.${CI_ENVIRONMENT_SLUG}-redirect.redirectregex.regex=^https?://${HOST}/(.*)"
      - "traefik.http.middlewares.${CI_ENVIRONMENT_SLUG}-redirect.redirectregex.replacement=https://www.${HOST}/$${1}"
      - "traefik.http.routers.${CI_ENVIRONMENT_SLUG}-ssl.middlewares=${CI_ENVIRONMENT_SLUG}-redirect"
      - "traefik.http.routers.${CI_ENVIRONMENT_SLUG}-ssl.entryPoints=websecure"
      - "traefik.http.routers.${CI_ENVIRONMENT_SLUG}-ssl.rule=host(`${HOST}`, `www.${HOST}`)"
      - "traefik.http.routers.${CI_ENVIRONMENT_SLUG}-ssl.tls=true"
      - "traefik.http.routers.${CI_ENVIRONMENT_SLUG}-ssl.tls.certResolver=leresolver"
      - "traefik.http.routers.${CI_ENVIRONMENT_SLUG}-ssl.service=${CI_ENVIRONMENT_SLUG}-ssl"
      - "traefik.http.services.${CI_ENVIRONMENT_SLUG}-ssl.loadBalancer.server.port=8000"
      - "traefik.docker.network=web"
    networks:
      - web
      - default

  memcached:
    restart: always
    networks:
      - default

  ipfs:
    restart: always
    logging:
      driver: journald
    image: ipfs/go-ipfs:latest
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=ipfsdata
    volumes:
      - ./data/ipfs:/ipfsdata
    networks:
      - web
      - default
    ports:
      - "4001:4001"

  postgres:
    restart: always
    networks:
      - default
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./dump:/dump
    labels:
      - "io.yourlabs.compose.mkdir=./dump,./data/postgres,./log/postgres:999:999:0700"

networks:
  web:
    external: true
