version: '3.5'
services:
  django:
    # DO NOT REMOVE
    # Ensures we keep access logs accross re-creates of the container
    # Use journalctl CONTAINER_NAME=production_backend_1 to see them
    logging:
      driver: journald

    build:
      dockerfile: Dockerfile
      context: .
    volumes:
    - /app/media
    - /tmp
    environment:
    - HOST
    - PROTO
    - ADMINS
    - BASICAUTH_ENABLE
    - CI_ENVIRONMENT_NAME
    - CI_COMMIT_SHA
    - SENTRY_DSN
    - MEDIA_ROOT=/app/media
    - LOG_DIR=/app/log
    - IPFS_PATH=/app/.ipfs
    - DB_HOST=postgres
    - DB_NAME=electeez
    - DB_USER=electeez
    - DB_PASS=electeez
    - DB_ENGINE=django.db.backends.postgresql
    - EMAIL_HOST
    - EMAIL_HOST_USER
    - EMAIL_HOST_PASSWORD
    - EMAIL_USE_SSL
    - EMAIL_USE_TLS
    - EMAIL_PORT
    - DEFAULT_FROM_EMAIL
    - MEMCACHED_HOST=memcached
    - SECRET_KEY
    - DEBUG=
    - PYTHONPATH=/app
    - DJANGO_SETTINGS_MODULE

  memcached:
    logging:
      driver: journald
    image: memcached:1.6-alpine

  postgres:
    logging:
      driver: journald
    image: postgres:13
    environment:
    - POSTGRES_DB=electeez
    - POSTGRES_USER=electeez
    - POSTGRES_PASSWORD=electeez
    volumes:
    - /var/lib/postgresql/data
    command:
        - "postgres"
        - "-c"
        - "logging_collector=on"
        - "-c"
        - "log_statement=all"
        - "-c"
        - "log_destination=stderr"
        - "-c"
        - "log_filename=postgresql.log"
        - "-c"
        - "log_min_duration_statement=0"
        - "-c"
        - "log_checkpoints=on"
        - "-c"
        - "log_connections=on"
        - "-c"
        - "log_disconnections=on"
        - "-c"
        - "log_lock_waits=on"
        - "-c"
        - "log_temp_files=0"
        - "-c"
        - "log_autovacuum_min_duration=0"
        - "-c"
        - "log_error_verbosity=default"
        - "-c"
        - "shared_preload_libraries=pg_stat_statements"
        - "-c"
        - "pg_stat_statements.track=all"
        - "-c"
        - "max_connections=200"

